### ISSUE TITLE
Feature request: Automatically warn on memory consumption

### ISSUE THREAD

**Issue by HyperBrain** [arabold/serverless-sentry-plugin#1]
Additionally to warn as soon as half of the available timeout time has been used, it would be also critical to add an automatic warning, when 3/4 or some other configurable percentage of the provided lambda memory has been consumed, as it's hard to find out if the assigned memory is nearing the limit over time.
This happens especially when using Babel or other transformations that change their behavior on updates and create faster but more memory hungry code.

**Comment by arabold** [comment]
Yes, that would be a great feature. 75% memory consumption should definitely generate a warning.

**Comment by arabold** [comment]
Check out v0.1.4 which I've just released 8-)
Additional testing is very welcome.
