### ISSUE TITLE
Direction for other language support (python)

### ISSUE THREAD

**Issue by kevgliss** [arabold/serverless-sentry-plugin#10]
You mention `Other platforms can be added easily by providing a respective integration library`. I am interested in adding support for python but am a bit lost on where exactly you foresee this library supporting other languages. I think there are two core parts to supporting a new language:

- Exception Handler Wrapper
- Raven setup

But I am not sure how we would traverse the python/node boundary.

Any insight?

**Comment by arabold** [comment]
Hi @kevgliss . Thanks for your interest. I really appreciate.

The plugin itself (this code here) does not need to be ported as it's working for all platforms running on AWS. There's an additional [serverless-sentry-lib](https://github.com/arabold/serverless-sentry-lib) that integrates with the user's Node.js code. This lib needs to be ported to Python.

The plugin passes configuration options to the Lambda (and thus to the lib) via environment variables:
 * SENTRY_DSN
 * SENTRY_ENVIRONMENT
 * SENTRY_RELEASE
 * SENTRY_AUTO_BREADCRUMBS
 * SENTRY_FILTER_LOCAL
 * SENTRY_CAPTURE_ERRORS
 * etc. (see https://github.com/arabold/serverless-sentry-lib#environment-variables)

So basically all you have to do is check these environment variables, load the [official Python Raven](https://github.com/getsentry/raven-python) module and configure it accordingly.

The Node.js library has some special tricks up its sleeve that are not necessary to be implemented in Python right away, but can be added over time:
* The Lambda start is automatically logged using a breadcrumb
* Check for local environment and forward only messages if deployed on Lambda: specifically check for IS_OFFLINE and IS_LOCAL here
* Tracking and alerting on memory usage: monitor memory and alert once 75% of allocated memory used
* Tracking and alerting on runtime: set a timeout to about 2/3 of the maximal runtime of the Lambda and alert if reached

Other features of the plugin, such as deployment notifications in Sentry, are available independently of the lib used.

Hope that helps. Let me know if any questions or issues arise.

**Comment by arabold** [comment]
You could even start to use the `serverless-sentry-plugin` _without_ writing a dedicated Pyhton library first. If you simply check for the given environment variables in your code (specifically the `SENTRY_*` ones) you can do pretty much all you want by passing them to the Python Client: Set `dsn` to `SENTRY_DSN`, `release` to `SENTRY_RELEASE`, `environment` to `SENTRY_ENVIRONMENT`, etc. See https://docs.sentry.io/clients/python/advanced/#client-arguments for the full list of parameters accepted by the Sentry client.

In addition, for Node we're automatically setting a couple of Sentry tags based on the environment variables available:
```js
{
  release: SENTRY_RELEASE,
  environment: SENTRY_ENVIRONMENT,
  tags: {
    lambda: AWS_LAMBDA_FUNCTION_NAME,
    version: AWS_LAMBDA_FUNCTION_VERSION,
    memory_size: AWS_LAMBDA_FUNCTION_MEMORY_SIZE,
    log_group: AWS_LAMBDA_LOG_GROUP_NAME,
    log_stream: AWS_LAMBDA_LOG_STREAM_NAME,
    service_name: SERVERLESS_SERVICE,
    stage: SERVERLESS_STAGE,
    alias: SERVERLESS_ALIAS,
    region: SERVERLESS_REGION || AWS_REGION
  }
}
```

The `AWS_LAMBDA_*` variables are set by the Lambda environment itself (might be different for Python?!), the `SERVERLESS_*` ones are optional and can be set by the user via the `serverless.yaml`. And finally the `SENTRY_*` environment variables are set by the`serverless-sentry-plugin`.

This should work right away. Then, if you have working code, it should be rather simple to extract the common functions into a dedicated library to share with the community.

**Comment by kevgliss** [comment]
Ah, that makes much more sense now. There are already quite a few integrations for [`raven-python`](https://github.com/getsentry/raven-python/tree/master/raven/contrib) that I can use as examples. 

Once created I can simply use this plugin to layer in the necessary serverless environment variables. 

Those tags look super useful, thanks!

**Comment by kevgliss** [comment]
FYI I have started this work here:
https://github.com/Netflix-Skunkworks/raven-python-lambda

Still very much a WIP. Thanks for the guidance!

Cheers,
Kevin

**Comment by arabold** [comment]
Very cool! Let me know if you need anything. I'm gonna link the python lib here in the main repo, too, so people can find it in future.
