### ISSUE TITLE
Using random version make serverless configuration inconsistant

### ISSUE THREAD

**Issue by vcarel** [arabold/serverless-sentry-plugin#12]
When configuring release version as "random", the underlying serverless configuration is invalid.

In `invalid cloudformation-template-update-stack.json`, we get something like:

        "Environment": {
          "Variables": {
            "NODE_ENV": "production",
            "SENTRY_DSN_CLIENT": "...",
            "SENTRY_DSN": "..."
            "SENTRY_RELEASE": {
              "isFulfilled": true,
              "isRejected": false,
              "fulfillmentValue": "206cad0e9012458e88835839fd8aab33"
            },

This fails on deployment because an environment variable cannot be (obviously) an object.

**Comment by arabold** [comment]
Thanks for this bug report. I've released 1.0.0-rc.4 which fixes random version number generation. Let me know if this solves your problem.

**Comment by vcarel** [comment]
Hi @arabold, just to confirm it's fixed in 1.0.0-rc.4.
Thanks a lot :+1:
