### ISSUE TITLE
Add custom User Context

### ISSUE THREAD

**Issue by andypmw** [arabold/serverless-sentry-plugin#21]
I am not using Cognito for Lambda authentication, but using custom authentication using Lambda NodeJS.

How I can set additional context such as:

```
  Raven.setContext({
    user: {
      email: 'matt@example.com',
      id: '123'
    }
  });
```

Thank your very much

**Comment by arabold** [comment]
Raven is a singleton and you should be able to use it the same way as before. The code above should actually work in my expectation though I didn't try it. However, it might overwrite whatever the serverless plugin itself already has set.

Following the instructions of the [Sentry docs](https://docs.sentry.io/clients/node/) should also work:

```js
Raven.context(function () {
  Raven.setContext({
    user: {
      email: 'matt@example.com',
      id: '123'
    }
  });
  // errors thrown here will be associated with matt
});
// errors thrown here will not be associated with matt
```

The important piece is the `Raven.context()` wrapping your code. I have also never tried it this way, but it _should_ work.

What issues are you seeing?

**Comment by andypmw** [comment]
Hi @arabold , thank you so much for your response.

I am using AWS Lambda for backend of a mobile app, paired with Amazon API Gateway. I need to track which user(s) affected by captured error by Raven/Sentry, so when we have fixed the error, we can contact our user.

I have try to set custom data such as User ID, Email, Name, etc. And yeah, you are right, whatever was set by serverless plugin is gone:

- api_id
- api_state
- environment
- http_method
- log_group
- log_stream
- version


What I need is to keep all these nice information, and add custom context info. Maybe something like this:

```
SentryPlugin.addContextInfo({
  user: 'andypmw',
  name: 'Andy',
  email: 'andy@amazing.xyz'
});
```

Any idea? I need it badly. Maybe I can dig your code and the method, if it does not exist yet.


Cheers,
Andy P.

**Comment by arabold** [comment]
Sorry, I've overlooked your response. Isn't `Raven.mergeContext()` what you're looking for?

**Comment by andypmw** [comment]
Yes you are right ....

I have added `Raven.mergeContext()` and now I can add custom context data without wipe-out all context set by your plugin.

Thank you so much!
