### ISSUE TITLE
Issue not tracked in Sentry

### ISSUE THREAD

**Issue by ManuelFrigerio** [arabold/serverless-sentry-plugin#27]
Hi, I've followed the instructions and installed the plugin on Lambda.
However, when I then trigger a very obvious error, it's not picked up in Sentry.

Here's my code:

```
'use strict';
const SparkPost = require('sparkpost');
const { decrypt, } = require('../crypto.js');
const RavenLambdaWrapper = require("serverless-sentry-lib");

// Wrap handler for automated error and exception logging
const ravenConfig = {
  captureErrors: true,
  captureUnhandledRejections: true,
  captureMemoryWarnings: true,
  captureTimeoutWarnings: true,
  ravenClient: require("raven") // don't forget!
};

module.exports.index = RavenLambdaWrapper.handler(ravenConfig, (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = true;
  const keys = event.requestContext.authorizer;
  const body = JSON.parse(event.body);
  console.log('event', JSON.stringify(body, 3));
  const response = {
    statusCode: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Credentials': true,
    },
    body: '',
  };

  const client = new SparkPost(keys.SparkPostKey);

  const RECIPIENT = body.RECIPIENT;
  const TEMPLATE_ID = body.TEMPLATE_ID;
  const CAMPAIGN_ID = body.CAMPAIGN_ID;
  const SUBSTITUTION_DATA = body.SUBSTITUTION_DATA;

  try {
    if (SUBSTITUTION_DATA && SUBSTITUTION_DATA.confirmation_link) {
      SUBSTITUTION_DATA.confirmation_link = decrypt(SUBSTITUTION_DATA.confirmation_link);
    }
  } catch (err) {
    console.log('to decryption err', err);
    response.statusCode = 400;
    response.body = JSON.stringify({
      status: 'Failed',
      error: 'Decryption error in \'confirmation_link\'',
    });
    return callback(null, response);
  }

  client.transmissions.send({
    options: {
      track_opens: true,
      track_clicks: true,
      transactional: true,
      ip_pool: "trans2"
    },
    campaign_id: CAMPAIGN_ID,
    content: {
      template_id: TEMPLATE_ID
    },
    substitution_data: SUBSTITUTION_DATA,
    recipients: RECIPIENT
  })
    .then(data => {
      console.log("Email has been sent. ", data);
      response.body = JSON.stringify({
        success: true,
        data: data,
      });
      callback(null, response);

    })
    .catch(err => {
      console.log(err);
      response.statusCode = 400;
      response.body = JSON.stringify({
        success: false,
        error: err,
      });
      callback(null, response);

    });

});
```
This is my serverless.yml file

```
service: saas-service

plugins:
  - serverless-webpack
  - serverless-sentry

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.environment.AwsRegion}
  stage: ${opt:stage}
  timeout: 30
  memorySize: 512

custom:
  environment: ${file(./config.json):${opt:stage}}
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
        - crypto
  sentry:
    dsn: https://XXX@sentry.io/YYY # URL provided by Sentry

functions:
  Authorizer:
    handler: functions/authorizer/authorizer.index
    environment:
      Environment: ${opt:stage}

  ConfirmationEmail:
    handler: functions/mail/confirmation_email.index
    events:
    - http:
        path: confirmation_email/
        method: post
        cors: true
        authorizer:
          name: Authorizer
          resultTtlInSeconds: 0
          identitySource: method.request.header.Authorization
          type: token
    environment:
      Environment: ${opt:stage}

resources:
	Resources:
	  GatewayResponseDefault4XX:
	    Type: 'AWS::ApiGateway::GatewayResponse'
	    Properties:
	      ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
	      ResponseType: DEFAULT_4XX
	      RestApiId:
	        Ref: 'ApiGatewayRestApi'
```

If I send a wrong SUBSTITUTION_DATA.confirmation_link the Lambda functions breaks (correctly) and I can see the log in CloudWatch, but Sentry doesn't pick anything up.
Ideas?

**Comment by JakeChampion** [comment]
I believe this is because you are catching the error, which implies it has been handled by the application.

if you rethrow the error after you send your responses, Sentry will report them.

```js
'use strict';
const SparkPost = require('sparkpost');
const { decrypt, } = require('../crypto.js');
const RavenLambdaWrapper = require("serverless-sentry-lib");

// Wrap handler for automated error and exception logging
const ravenConfig = {
  captureErrors: true,
  captureUnhandledRejections: true,
  captureMemoryWarnings: true,
  captureTimeoutWarnings: true,
  ravenClient: require("raven") // don't forget!
};

module.exports.index = RavenLambdaWrapper.handler(ravenConfig, (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = true;
  const keys = event.requestContext.authorizer;
  const body = JSON.parse(event.body);
  console.log('event', JSON.stringify(body, 3));
  const response = {
    statusCode: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Credentials': true,
    },
    body: '',
  };

  const client = new SparkPost(keys.SparkPostKey);

  const RECIPIENT = body.RECIPIENT;
  const TEMPLATE_ID = body.TEMPLATE_ID;
  const CAMPAIGN_ID = body.CAMPAIGN_ID;
  const SUBSTITUTION_DATA = body.SUBSTITUTION_DATA;

  try {
    if (SUBSTITUTION_DATA && SUBSTITUTION_DATA.confirmation_link) {
      SUBSTITUTION_DATA.confirmation_link = decrypt(SUBSTITUTION_DATA.confirmation_link);
    }
  } catch (err) {
    console.log('to decryption err', err);
    response.statusCode = 400;
    response.body = JSON.stringify({
      status: 'Failed',
      error: 'Decryption error in \'confirmation_link\'',
    });
    callback(null, response);
    throw err;
  }

  client.transmissions.send({
    options: {
      track_opens: true,
      track_clicks: true,
      transactional: true,
      ip_pool: "trans2"
    },
    campaign_id: CAMPAIGN_ID,
    content: {
      template_id: TEMPLATE_ID
    },
    substitution_data: SUBSTITUTION_DATA,
    recipients: RECIPIENT
  })
    .then(data => {
      console.log("Email has been sent. ", data);
      response.body = JSON.stringify({
        success: true,
        data: data,
      });
      callback(null, response);

    })
    .catch(err => {
      console.log(err);
      response.statusCode = 400;
      response.body = JSON.stringify({
        success: false,
        error: err,
      });
      callback(null, response);
      throw err;
    });

});
```

**Comment by ManuelFrigerio** [comment]
Hi @JakeChampion, I did that but the error still doesn't show up in Sentry.
I'm stuck to the **Waiting for events…** page...

**Comment by demetrio812** [comment]
Hello, same for me here, using Typescript and the new handler version, I even tried to call `Raven.captureMessage("Hello from Lambda!");` without success.

I've setup the release and it work, but it doesn't log any message...how can I debug it?

**Comment by ppanchal97** [comment]
> I believe this is because you are catching the error, which implies it has been handled by the application.
> 
> if you rethrow the error after you send your responses, Sentry will report them.
> 
> ```js
> 'use strict';
> const SparkPost = require('sparkpost');
> const { decrypt, } = require('../crypto.js');
> const RavenLambdaWrapper = require("serverless-sentry-lib");
> 
> // Wrap handler for automated error and exception logging
> const ravenConfig = {
>   captureErrors: true,
>   captureUnhandledRejections: true,
>   captureMemoryWarnings: true,
>   captureTimeoutWarnings: true,
>   ravenClient: require("raven") // don't forget!
> };
> 
> module.exports.index = RavenLambdaWrapper.handler(ravenConfig, (event, context, callback) => {
>   context.callbackWaitsForEmptyEventLoop = true;
>   const keys = event.requestContext.authorizer;
>   const body = JSON.parse(event.body);
>   console.log('event', JSON.stringify(body, 3));
>   const response = {
>     statusCode: 200,
>     headers: {
>       'Access-Control-Allow-Origin': '*',
>       'Access-Control-Allow-Credentials': true,
>     },
>     body: '',
>   };
> 
>   const client = new SparkPost(keys.SparkPostKey);
> 
>   const RECIPIENT = body.RECIPIENT;
>   const TEMPLATE_ID = body.TEMPLATE_ID;
>   const CAMPAIGN_ID = body.CAMPAIGN_ID;
>   const SUBSTITUTION_DATA = body.SUBSTITUTION_DATA;
> 
>   try {
>     if (SUBSTITUTION_DATA && SUBSTITUTION_DATA.confirmation_link) {
>       SUBSTITUTION_DATA.confirmation_link = decrypt(SUBSTITUTION_DATA.confirmation_link);
>     }
>   } catch (err) {
>     console.log('to decryption err', err);
>     response.statusCode = 400;
>     response.body = JSON.stringify({
>       status: 'Failed',
>       error: 'Decryption error in \'confirmation_link\'',
>     });
>     callback(null, response);
>     throw err;
>   }
> 
>   client.transmissions.send({
>     options: {
>       track_opens: true,
>       track_clicks: true,
>       transactional: true,
>       ip_pool: "trans2"
>     },
>     campaign_id: CAMPAIGN_ID,
>     content: {
>       template_id: TEMPLATE_ID
>     },
>     substitution_data: SUBSTITUTION_DATA,
>     recipients: RECIPIENT
>   })
>     .then(data => {
>       console.log("Email has been sent. ", data);
>       response.body = JSON.stringify({
>         success: true,
>         data: data,
>       });
>       callback(null, response);
> 
>     })
>     .catch(err => {
>       console.log(err);
>       response.statusCode = 400;
>       response.body = JSON.stringify({
>         success: false,
>         error: err,
>       });
>       callback(null, response);
>       throw err;
>     });
> 
> });
> ```

Thank you - I was facing the same issue where sentry would not pick up any errors logged within the lambda - the solution was to throw an error manually in the catch block such as `throw err;`
