### ISSUE TITLE
Unified Node.js SDK

### ISSUE THREAD

**Issue by Vadorequest** [arabold/serverless-sentry-plugin#29]
Is there any way to use this plugin with the latest version of the Sentry SDK? They have deprecated the Raven version.

**Comment by marcosfede** [comment]
any updates?

**Comment by aheissenberger** [comment]
I did implemented the required changes and added a pull request
https://github.com/arabold/serverless-sentry-lib/pull/17

**Comment by mskutin** [comment]
@arabold any chance this can be reviewed and merged?

**Comment by demsey2** [comment]
any update on this PR?

**Comment by polosatyi** [comment]
any updates?

**Comment by arabold** [comment]
v2 has been released a couple of weeks ago.
