### ISSUE TITLE
0.2 release breaks lambda

### ISSUE THREAD

**Issue by vanerleo** [arabold/serverless-sentry-plugin#3]
Hi,
after upgrading to 0.2 , lambda execution never completes (gives an error "Task timed out after")
downgrading back to 0.1.4, lambda function works fine .

feels like something is not being returned or callback not bing called

**Comment by arabold** [comment]
Interesting. I haven't encountered this problem yet. Are you using Node 4.3 or an older runtime and what timeout value do you use for your Lambda? It would be great if you could post some related code to reproduce it.

My suspicion is that one of the monitoring timeouts of the plugin (such as the memory or the execution time warning) isn't shut down properly for some reason and thus keeps the main loop active despite your code already having finished.

**Comment by arabold** [comment]
@vanerleo check out 0.2.1 -- I think I found the mistake. Give it a shot if you can.

**Comment by vanerleo** [comment]
yep, looks like you fixed it,
thanks
