### ISSUE TITLE
Add support for filtering events

### ISSUE THREAD

**Issue by AlexSun98** [arabold/serverless-sentry-plugin#40]
Does the lib support a feature of filtering events? (don't wana assign a new instance of sentry)

Reference: 
https://docs.sentry.io/platforms/node/guides/aws-lambda/configuration/filtering

`import * as Sentry from "@sentry/browser";

init({
  beforeSend(event, hint) {
    const error = hint.originalException;
    if (
      error &&
      error.message &&
      error.message.match(/database unavailable/i)
    ) {
      event.fingerprint = ["database-unavailable"];
    }
    return event;
  },
});`

**Comment by arabold** [comment]
This has been cross-posted and answered here already:
https://github.com/arabold/serverless-sentry-lib/issues/28
