### ISSUE TITLE
Any progress on uploading source maps?

### ISSUE THREAD

**Issue by ffxsam** [arabold/serverless-sentry-plugin#42]
Are there still plans to work on this? If one of the repo maintainers wants to work together on this, I'm game. Right now I have to decide between using this plugin (which rocks), or the `SentryWebpackPlugin` (not quite as good) which _does_ upload source maps.

**Comment by kiorq** [comment]
Any update on this?

**Comment by arabold** [comment]
Sorry for the belated reply. There's actually no reason you couldn't use both the `SentryWebpackPlugin` and the `serverless-sentry-plugin` at the same time. In fact, I'm using already both in one of my projects. `SentryWebpackPlugin` runs during packaging and will upload your source maps to Sentry. The `serverless-sentry-plugin` allows you to simplify the integration of your Lambda JavaScript code itself with Sentry, e.g. it will automatically watch for unhandled exceptions and generate timeout warnings for you.

Having that said, there still is an advantage of adding the functionality to the `serverless-sentry-plugin` itself. It would simplify the setup and remove redundant options. It's still an open feature request, unfortunately. If anybody wants to pick it up for implementation, be my guest. I'm not sure if I'll get to it myself anytime soon.
