### ISSUE TITLE
Differences between this and official @sentry/serverless package

### ISSUE THREAD

**Issue by dijonkitchen** [arabold/serverless-sentry-plugin#43]
Is this package still relevant compared to Sentry's official one? 
https://docs.sentry.io/platforms/node/guides/aws-lambda/

**Comment by arabold** [comment]
`@sentry/serverless` is partly based on the work in this plugin. Unfortunately, I haven't found the time to do an in-depth comparison myself, but from my understanding, this plugin can be deprecated sooner or later. There might still be some difference in feature set and flexibility, but I'm sure the official Sentry integration will get better in time.

**Comment by webjunkie** [comment]
>this plugin can be deprecated sooner or later

It would be nice if this plugin has a big note about that in the main README and directs people to at least check out Sentry's official package themselves.
