### ISSUE TITLE
Feature Request: Break deploy when raven is missing as dependency

### ISSUE THREAD

**Issue by HyperBrain** [arabold/serverless-sentry-plugin#5]
**Rationale**
The lambda code generated by the plugin is dependent on raven and will not ever start, but immediately break out with an exception, if the dependent module is missing. If you use the optimizer plugin, it is very hard so see what you did wrong. This is something that easily can happen when setting up a new lambda that uses the plugin.
Dependencies introduced by plugins that make the code crash when missing, should be either installed by the plugin or any use of the generated function should be denied by it.

**Proposal**
On function deploy the plugin should break out if raven is not found as installed dependency.

**Comment by arabold** [comment]
A new version 1.0.0-rc.1 of this plugin that works with Serverless 1.x is available now. I'm going to close this issue.
