### ISSUE TITLE
Function Timeouts lack of information

### ISSUE THREAD

**Issue by forgetalex** [arabold/serverless-sentry-plugin#69]
In case of a function timeout the information provided is very modest.

The information is as follows:
`{
Records: [
[Object]
]
}`

It would be good to see the whole output as a string, is there a way to do so?

Thank you! Alex

**Comment by KillDozerX2** [comment]
This is more of an issue for [serverless-sentry-lib](https://github.com/arabold/serverless-sentry-lib). Specifically with installTimers around [here](https://github.com/arabold/serverless-sentry-lib/blob/e0b4c26084d1c7c98a0379ade343ae2b699d09a4/src/index.ts#L217)

**Comment by forgetalex** [comment]
Thanks for your help!
